### PR TITLE
bump up version of logback

### PR DESCRIPTION
**Pull request by dinesh-flipkart**

### CODE REVIEW

**Comment by pmohankumar** [comment]
@dinesh-flipkart , can you paste mvn dependency:tree for logback form your branch?

In 4.x it looks like this
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.3:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.3:compile
[INFO] +- ch.qos.logback:logback-access:jar:1.1.3:compile

So 1.1.3 isn't bringing in any transitive dependencies in current 4.x of poseidon. Want to make sure, 1.1.5 doesn't bring in any other new dependencies.

**Comment by dinesh-flipkart** [comment]
@pmohankumar can we can publish these changes in current poseidon version (4.5.1-SNAPSHOT) ?

**Comment by dinesh-flipkart** [comment]
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.5:compile
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.5:compile
[INFO] +- ch.qos.logback:logback-access:jar:1.1.5:compile

**Comment by pmohankumar** [comment]
cool. LGTM

**Pull request merged**
